// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: article.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CovidLib {

  /// <summary>Holder for reflection information generated from article.proto</summary>
  public static partial class ArticleReflection {

    #region Descriptor
    /// <summary>File descriptor for article.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArticleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1hcnRpY2xlLnByb3RvEghDb3ZpZExpYiJuCgdBcnRpY2xlEhoKElppcHBl",
            "ZEpzb25GaWxlTmFtZRgBIAEoDBIcChRaaXBwZWRCdWNrZXRGaWxlTmFtZRgC",
            "IAEoDBITCgtaaXBwZWRUaXRsZRgDIAEoDBIUCgxDb3VudGVySW5kZXgYBCAB",
            "KAUiKwoIQXJ0aWNsZXMSHwoETGlzdBgBIAMoCzIRLkNvdmlkTGliLkFydGlj",
            "bGUirQEKGlN0cmluZ1RvQXJ0aWNsZXNEaWN0aW9uYXJ5EkgKCkRpY3Rpb25h",
            "cnkYASADKAsyNC5Db3ZpZExpYi5TdHJpbmdUb0FydGljbGVzRGljdGlvbmFy",
            "eS5EaWN0aW9uYXJ5RW50cnkaRQoPRGljdGlvbmFyeUVudHJ5EgsKA2tleRgB",
            "IAEoCRIhCgV2YWx1ZRgCIAEoCzISLkNvdmlkTGliLkFydGljbGVzOgI4AWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CovidLib.Article), global::CovidLib.Article.Parser, new[]{ "ZippedJsonFileName", "ZippedBucketFileName", "ZippedTitle", "CounterIndex" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CovidLib.Articles), global::CovidLib.Articles.Parser, new[]{ "List" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CovidLib.StringToArticlesDictionary), global::CovidLib.StringToArticlesDictionary.Parser, new[]{ "Dictionary" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Article : pb::IMessage<Article>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Article> _parser = new pb::MessageParser<Article>(() => new Article());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Article> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CovidLib.ArticleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Article() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Article(Article other) : this() {
      zippedJsonFileName_ = other.zippedJsonFileName_;
      zippedBucketFileName_ = other.zippedBucketFileName_;
      zippedTitle_ = other.zippedTitle_;
      counterIndex_ = other.counterIndex_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Article Clone() {
      return new Article(this);
    }

    /// <summary>Field number for the "ZippedJsonFileName" field.</summary>
    public const int ZippedJsonFileNameFieldNumber = 1;
    private pb::ByteString zippedJsonFileName_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ZippedJsonFileName {
      get { return zippedJsonFileName_; }
      set {
        zippedJsonFileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ZippedBucketFileName" field.</summary>
    public const int ZippedBucketFileNameFieldNumber = 2;
    private pb::ByteString zippedBucketFileName_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ZippedBucketFileName {
      get { return zippedBucketFileName_; }
      set {
        zippedBucketFileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ZippedTitle" field.</summary>
    public const int ZippedTitleFieldNumber = 3;
    private pb::ByteString zippedTitle_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString ZippedTitle {
      get { return zippedTitle_; }
      set {
        zippedTitle_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "CounterIndex" field.</summary>
    public const int CounterIndexFieldNumber = 4;
    private int counterIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CounterIndex {
      get { return counterIndex_; }
      set {
        counterIndex_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Article);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Article other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ZippedJsonFileName != other.ZippedJsonFileName) return false;
      if (ZippedBucketFileName != other.ZippedBucketFileName) return false;
      if (ZippedTitle != other.ZippedTitle) return false;
      if (CounterIndex != other.CounterIndex) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ZippedJsonFileName.Length != 0) hash ^= ZippedJsonFileName.GetHashCode();
      if (ZippedBucketFileName.Length != 0) hash ^= ZippedBucketFileName.GetHashCode();
      if (ZippedTitle.Length != 0) hash ^= ZippedTitle.GetHashCode();
      if (CounterIndex != 0) hash ^= CounterIndex.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ZippedJsonFileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ZippedJsonFileName);
      }
      if (ZippedBucketFileName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(ZippedBucketFileName);
      }
      if (ZippedTitle.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(ZippedTitle);
      }
      if (CounterIndex != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CounterIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ZippedJsonFileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(ZippedJsonFileName);
      }
      if (ZippedBucketFileName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(ZippedBucketFileName);
      }
      if (ZippedTitle.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(ZippedTitle);
      }
      if (CounterIndex != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(CounterIndex);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ZippedJsonFileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ZippedJsonFileName);
      }
      if (ZippedBucketFileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ZippedBucketFileName);
      }
      if (ZippedTitle.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(ZippedTitle);
      }
      if (CounterIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CounterIndex);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Article other) {
      if (other == null) {
        return;
      }
      if (other.ZippedJsonFileName.Length != 0) {
        ZippedJsonFileName = other.ZippedJsonFileName;
      }
      if (other.ZippedBucketFileName.Length != 0) {
        ZippedBucketFileName = other.ZippedBucketFileName;
      }
      if (other.ZippedTitle.Length != 0) {
        ZippedTitle = other.ZippedTitle;
      }
      if (other.CounterIndex != 0) {
        CounterIndex = other.CounterIndex;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ZippedJsonFileName = input.ReadBytes();
            break;
          }
          case 18: {
            ZippedBucketFileName = input.ReadBytes();
            break;
          }
          case 26: {
            ZippedTitle = input.ReadBytes();
            break;
          }
          case 32: {
            CounterIndex = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            ZippedJsonFileName = input.ReadBytes();
            break;
          }
          case 18: {
            ZippedBucketFileName = input.ReadBytes();
            break;
          }
          case 26: {
            ZippedTitle = input.ReadBytes();
            break;
          }
          case 32: {
            CounterIndex = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Articles : pb::IMessage<Articles>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Articles> _parser = new pb::MessageParser<Articles>(() => new Articles());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Articles> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CovidLib.ArticleReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Articles() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Articles(Articles other) : this() {
      list_ = other.list_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Articles Clone() {
      return new Articles(this);
    }

    /// <summary>Field number for the "List" field.</summary>
    public const int ListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::CovidLib.Article> _repeated_list_codec
        = pb::FieldCodec.ForMessage(10, global::CovidLib.Article.Parser);
    private readonly pbc::RepeatedField<global::CovidLib.Article> list_ = new pbc::RepeatedField<global::CovidLib.Article>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::CovidLib.Article> List {
      get { return list_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Articles);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Articles other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!list_.Equals(other.list_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= list_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      list_.WriteTo(output, _repeated_list_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      list_.WriteTo(ref output, _repeated_list_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += list_.CalculateSize(_repeated_list_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Articles other) {
      if (other == null) {
        return;
      }
      list_.Add(other.list_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            list_.AddEntriesFrom(input, _repeated_list_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            list_.AddEntriesFrom(ref input, _repeated_list_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class StringToArticlesDictionary : pb::IMessage<StringToArticlesDictionary>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<StringToArticlesDictionary> _parser = new pb::MessageParser<StringToArticlesDictionary>(() => new StringToArticlesDictionary());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StringToArticlesDictionary> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CovidLib.ArticleReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringToArticlesDictionary() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringToArticlesDictionary(StringToArticlesDictionary other) : this() {
      dictionary_ = other.dictionary_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StringToArticlesDictionary Clone() {
      return new StringToArticlesDictionary(this);
    }

    /// <summary>Field number for the "Dictionary" field.</summary>
    public const int DictionaryFieldNumber = 1;
    private static readonly pbc::MapField<string, global::CovidLib.Articles>.Codec _map_dictionary_codec
        = new pbc::MapField<string, global::CovidLib.Articles>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::CovidLib.Articles.Parser), 10);
    private readonly pbc::MapField<string, global::CovidLib.Articles> dictionary_ = new pbc::MapField<string, global::CovidLib.Articles>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, global::CovidLib.Articles> Dictionary {
      get { return dictionary_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StringToArticlesDictionary);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StringToArticlesDictionary other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!Dictionary.Equals(other.Dictionary)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= Dictionary.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      dictionary_.WriteTo(output, _map_dictionary_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      dictionary_.WriteTo(ref output, _map_dictionary_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += dictionary_.CalculateSize(_map_dictionary_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StringToArticlesDictionary other) {
      if (other == null) {
        return;
      }
      dictionary_.Add(other.dictionary_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            dictionary_.AddEntriesFrom(input, _map_dictionary_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            dictionary_.AddEntriesFrom(ref input, _map_dictionary_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
